<?php

namespace App\Model\Manager;

/**
 * Test class for BaseManager.
 * Generated by PHPUnit on 2012-08-28 at 14:22:07.
 */
class BaseManagerTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var BaseManager
   */
  protected $object;
  protected $app;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    #$this->app = require ROOT . '/bootstrap.php';
    #$this->baseManager = new \App\Model\Manager\BaseManager($app['mongo'], $app['config.database']);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @covers App\Model\Manager\BaseManager::getDb
   * @todo Implement testGetDb().
   */
  public function testGetDb() {
    $this->assertTrue(true);
  }

  /**
   * @covers App\Model\Manager\BaseManager::getCollection
   * @todo Implement testGetCollection().
   */
  public function testGetCollection() {
    $this->assertTrue(true);
  }

}

?>
